apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        name: redis-4
    spec:
      containers:
        - name: redis
          image: ironelder/kubernetes:redis-cluster
          ports:
            - name: redis
              containerPort: 7000
              protocol: TCP
            - name: cluster
              containerPort: 17000
              protocol: TCP
