apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-5
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        name: redis-5
    spec:
      containers:
        - name: redis
          image: ironelder/kubernetes:redis-cluster-same
          ports:
            - name: redis
              containerPort: 7001
              protocol: TCP
            - name: cluster
              containerPort: 17001
              protocol: TCP
