kind: Service
apiVersion: v1
metadata:
  name: redis-4
spec:
  selector:
    app: redis
    name: redis-4
  ports:
    - name: redis
      port: 7000
      targetPort: 7000
      protocol: TCP
    - name: cluster
      port: 17000
      targetPort: 17000
      protocol: TCP
  clusterIP: "192.168.0.114"
